[package]
name = "ussua"
version = "0.0.0"
edition = "2021"
authors = ["yulmwu (Kim Jun Young)"]
description = "Bytecode"
repository = "https://github.com/yulmwu/ussua"
license = "MIT"

[[bin]]
name = "bytecode"
path = "bin/main.rs"

[dependencies]
